<?php
echo '<table class="none">';
  echo '<tr>';
    echo '<td>';
      echo '<div class="container">';
        echo '<a href="index.php" class="btn-animation-02">';
          echo '<span>HOME<span></a>';
      echo '</div>';
    echo '</td>';
  echo '</tr>';
  echo '<tr>';
    echo '<td>';
      echo '<div class="container">';
        echo '<a href="profile.php" class="btn-animation-02">';
          echo '<span>PROFILE<span></a>';
      echo '</div>';
    echo '</td>';
  echo '</tr>';
  echo '<tr>';
    echo '<td>';
      echo '<div class="container">';
        echo '<a href="works.php" class="btn-animation-02">';
          echo '<span>WORKS<span></a>';
    echo '</div>';
    echo '</td>';
  echo '</tr>';
  echo '<tr>';
    echo '<td>';
      echo '<div class="container">';
        echo '<a href="contact.php" class="btn-animation-02">';
          echo '<span>CONTACT<span></a>';
      echo '</div>';
    echo '</td>';
  echo '</tr>';
echo '</table><!-- ボタンが格納されている。 -->';
?>
